### ISSUE TITLE
Video Aspect Ratio is not correct

### ISSUE THREAD

**Issue by ktprograms** [shogo4405/HaishinKit.kt#48]
**Describe the bug**
When streaming using HaishinStudio, the stream has a resolution of 640x360, but the resolution in Camera2Source is 640x480. I looked at the code, and it seems like the `resolution` variable is never set in `Camera2Source`, so the stream resolution isn't set either. Even if I manually set the stream resolution to be equal to the source resolution, the video still has the wrong aspect ratio.

I'm testing this with commit https://github.com/shogo4405/HaishinKit.kt/commit/513e5512c6193ced3913a78111896e721cbaa39f, since the next commit seems to have broken video streaming (only the audio is available in VLC).

**To Reproduce**
1. Run HaishinStudio
2. Open the stream in VLC
3. See wrong aspect ratio

**Expected behavior**
The video has the correct aspect ratio.

I don't actually understand how/where the "correct" aspect ratio comes from, the variable setting seems a bit circular to me.

**Screenshots**

(The object in frame is a cube)

| On Phone | In VLC |
|--|--|
| <img width="512px" src="https://user-images.githubusercontent.com/71804605/161666122-9a3d6e91-e540-4417-a2f0-2c854224de40.png" /> | <img width="512px" src="https://user-images.githubusercontent.com/71804605/161666176-5d4db88d-1eae-416b-98ce-b79a47337ba0.png" /> |

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - VLC media player 3.0.12.1 Vetinari (revision 3.0.12.1-0-g170157402b)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A02
 - OS: Android 11

**Comment by shogo4405** [comment]
Thank you fedback. I fixed it.

**ViewSize**
<img src="https://user-images.githubusercontent.com/810189/162605778-61e9c51a-4152-4605-a194-9ceac192df5e.png" width=300 />

|Before|After|
|:-:|:-:|
|<img width="637" alt="スクリーンショット 2022-04-10 15 36 21" src="https://user-images.githubusercontent.com/810189/162605781-13407be1-742c-40a0-b7bf-6e3a716514c2.png">|<img width="638" alt="スクリーンショット 2022-04-10 15 02 36" src="https://user-images.githubusercontent.com/810189/162605782-5afeea41-f448-4381-aa12-e7f055d9235d.png">|

**Comment by ktprograms** [comment]
Thanks! It's working great!

**Comment by ktprograms** [comment]
Sorry, it's still broken.

When I put `cameraSource.resolution = Size(480, 640)` in the `onResume()` method of the example app's CameraTabFragment, both the view on the phone and the stream are stretched.
